syntax = "proto3";

package searchium.v2;

import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service SearchiumService { 
  // TODO: Replace with capabilities/version negotiation
  rpc Hello(HelloRequest) returns (HelloResponse);
  
  rpc RegisterFolder(FolderRegisterRequest) returns (stream IndexUpdate);
  rpc UnregisterFolder(FolderUnregisterRequest) returns (GenericResponse);
  
  rpc SearchFilePaths(stream FilePathSearchRequest) returns (stream FilePathSearchResponse);
  rpc SearchFileContents(FileContentsSearchRequest) returns (FileContentsSearchResponse);
  rpc GetFileExtracts(FileExtractsRequest) returns (FileExtractsResponse);
  
  rpc SetConfiguration(ConfigurationRequest) returns (ConfigurationResponse);
  rpc GetProcessInfo(ProcessInfoRequest) returns (ProcessInfoResponse);
  rpc GetDatabaseDetails(DatabaseDetailsRequest) returns (DatabaseDetailsResponse);
  
  rpc GetStatus(StatusRequest) returns (stream StatusResponse);
}

message HelloRequest {
  string id = 1;  
}
message HelloResponse {
  string id = 1;
}

message ConfigurationRequest {
  uint32 concurrent_file_reads = 1; // Max number of files to try and load simultaneously 
  uint64 max_file_size = 2; // Max size of files to index
}

message ConfigurationResponse { 

}

enum GenericError {
  GENERIC_ERROR_NONE = 0;
}

message GenericResponse { 
  GenericError error = 1;
  string log_message = 2;
}

message FolderRegisterRequest {
  string path = 1;
  repeated string ignore_file_globs = 2;
  repeated string ignore_search_globs = 3;
}

message FolderUnregisterRequest { 
  string path = 1;
}

message IndexUpdate { 
  google.protobuf.Timestamp timestamp = 1;
  message FilesystemScanStart {}
  message FilesystemScanEnd {}
  message FileContentsLoaded {
    uint32 count = 1;
    uint32 total = 2;
    string path = 3;
  }
  oneof type { 
    FilesystemScanStart filesystem_scan_start = 10; 
    FilesystemScanEnd filesystem_scan_end = 11; 
    FileContentsLoaded file_contents_loaded = 12;
  }
}

message FilePathSearchRequest {
  string query = 1;
  uint32 max_results = 2;
}

message FilePathSearchResponse {
  repeated string results = 1;
  google.protobuf.Duration duration = 2;
}

enum FileContentsQueryType {
  PLAIN = 0;
  WILDCARD = 1;
  REGEX = 2;
}

message FileContentsSearchRequest {
  string query_string = 1;
  string file_path_pattern = 2;
  uint32 max_results = 3; 
  bool match_case = 4;
  bool match_whole_word = 5;
  FileContentsQueryType query_type = 6;
}

message FileContentsSpan { 
  uint32 offset_bytes = 1;
  uint32 length_bytes = 2;
}

// A file path and the location of one or more matches from a search request
message FileContentsSearchHit {
  // Path relative to the registered root
  string file_relative_path = 1;
  // Spans of text that matched the query
  repeated FileContentsSpan match_spans = 2;
}

// A set of matches from a certain registered root directory
message FileContentsSearchRootResult { 
  string root_path = 1;
  repeated FileContentsSearchHit hits = 2;
}

message FileContentsSearchResponse {
  repeated FileContentsSearchRootResult roots = 1;
}

message FileExtractsRequest { 
  string file_path = 1;
  repeated FileContentsSpan match_spans = 2;
  uint32 max_extract_length = 3;
}

message FileExtract {
  // Text extracted as context for the match
  string full_text = 1;
  // Offset in bytes within the file of full_text
  uint32 extract_offset_bytes = 2;
  // Length in bytes within the file of full_text.
  // May be different to length of full_text in bytes if file encoding is different.
  uint32 extract_length_bytes = 3;
  // 0-based number of line containing the match
  uint32 line_number = 4;
}
message FileExtractsResponse {
  string file_path = 1;
  repeated FileExtract file_extracts = 2;
}

message ProcessInfoRequest {

}
message ProcessInfoResponse {
  uint64 physical_memory = 1;
  uint64 virtual_memory = 2;
}

message DatabaseDetailsRequest {
}

message DatabaseDetailsResponse {
  repeated DatabaseDetailsRoot roots = 1;  
}
message DatabaseDetailsRoot {
  string root_path = 1;
  uint64 num_files_scanned = 2;
  uint64 num_directories_scanned = 3;
  uint64 num_searchable_files = 4;
  uint64 searchable_files_bytes = 5;
  uint64 num_binary_files = 6;
  uint64 binary_files_bytes = 7;
  repeated FilesByExtensionDetails searchable_files_by_extension = 8;
  repeated FilesByExtensionDetails binary_files_by_extension = 9;
  repeated LargeFileDetails large_searchable_files = 10;
  repeated LargeFileDetails large_binary_files = 11;
}
message FilesByExtensionDetails {
  string extension = 1;
  uint64 count = 2;
  uint64 bytes = 3;
}
message LargeFileDetails { 
  string path = 1;
  uint64 bytes = 2;
}

message StatusRequest {}
enum IndexState { 
  UNAVAILABLE = 0;
  READY = 1;
  INDEXING = 2;
  PAUSED = 3;
}
message StatusResponse { 
  IndexState state = 1;
  uint64 mem_usage = 2;  
  uint64 num_searchable_files = 3;
}