[package]
name = "searchium-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9.0"
tokio = { version ="1.27.0", features = ["rt", "rt-multi-thread"] }
serde = "1.0" 
prost = "0.11.0"
pbjson = "0.5.1"
tokio-stream = "0.1.12"
